### ISSUE TITLE
Newest update now redirects to */auth.owa instead

### ISSUE THREAD

**Issue by chrislachance** [3axap4eHko/OWA-pro#1]
For some reason it used to redirect right to my web app. Now it redirects to the right URL, but tags on /auth.owa at the end, which is a page that shows nothing but "Bad request" on the page.

**Comment by 3axap4eHko** [comment]
Where did you click for that?

**Comment by chrislachance** [comment]
The popover that launches from the icon has a mail & event icon. Those do
that.


*- Chris *(chrislachance.com) <http://chrislachance.com>

**Comment by 3axap4eHko** [comment]
Could you provide version of Exchange Server?
You can find it on login page
![image](https://cloud.githubusercontent.com/assets/1630657/17575339/6f9ae862-5f36-11e6-937d-927c49a7ddeb.png)

**Comment by chrislachance** [comment]
I don't seem to have that standard screen on login, so I can't find it. I
am using the newer style of Outlook (but not 365). This wasn't an issue in
the previous version.


*- Chris *(chrislachance.com) <http://chrislachance.com>

**Comment by 3axap4eHko** [comment]
I'll bring autologin to configuration, right now it will be just redirect to the OWA page

**Comment by chrislachance** [comment]
Awesome. Thanks!

- Chris
