### ISSUE TITLE
Manual refresh required for app to work.

### ISSUE THREAD

**Issue by FireWings2259** [3axap4eHko/OWA-pro#1]
I hate to be the first person to post a bug, but when I disconnect from a network then reconnect to a different network, Sleep or Hibernate I have to ether refresh the background.html page or reconfigure the email settings. My best guess to what is happening is that background.js/html is not getting a update after a said events.

Hope this helps
Fire

**Comment by akiirish** [comment]
Same, I didn't want to be the first either.

**Comment by FireWings2259** [comment]
I don't want to be pushy but is there an eta on this? I get it completely if your busy, @3axap4eHko, but normally you reply or label the bug by now.

**Comment by 3axap4eHko** [comment]
Fixed in 7.2
