### ISSUE TITLE
Office 365 Support

### ISSUE THREAD

**Issue by jonnyeom** [3axap4eHko/OWA-pro#10]
So the OWA url for the web app for Office 365 is just https://outlook.office.com/owa/.

After the *Authorization* step in the setup, I get this.

![image](https://user-images.githubusercontent.com/19575068/36038203-094786d6-0d8d-11e8-9d25-84039c6f1437.png)

From here, I am don't seem to be able to sign in.

Am I missing a step here? Could you provide more specific documentation if I am?

**Comment by theemstra** [comment]
Hi!

You should use the actual OWA url, not the proxied one: https://outlook.office365.com

**Comment by aleqcz** [comment]
Then I get Exchange server not found. Is it because my organization is using secondary auth on their server (owa redirects me to company login screen asking for 2fa code)?

**Comment by theemstra** [comment]
Hello @aleqcz,

So you're using an on-premises Office 365 implementation, or are you 'just' using 2FA?
If you use 2FA then you can use an [app password](https://support.office.com/en-us/article/create-an-app-password-for-office-365-3e7c860f-bda4-4441-a618-b53953ee1183).

If you in fact use on-premises then you might need a proxy, but I don't think that's supported by the author of the extension atm.
