### ISSUE TITLE
What should I do if our username don't require a domain?

### ISSUE THREAD

**Issue by sskydragon** [3axap4eHko/OWA-pro#2]
![image](https://cloud.githubusercontent.com/assets/15975606/17581631/768da828-5fd9-11e6-8875-92bdf07901b4.png)

The version of OWA extension asks for a domain prior than the username.
But our "Outlook Web App" don't need the info for login .....
(It works at previous versions.)

May I skip the domain check of extension, 
or, is there any example to migrate setting from previous version to this one?
Thanks.

**Comment by paulthiggins** [comment]
Hi, I'm also affected by this problem - I don't have a domain (that I know of), in the previous version, I used my email address as the Username.

**Comment by 3axap4eHko** [comment]
Unfortunately, there are no migration guide. You should reinstall extension to avoid issues from 4th version

**Comment by 3axap4eHko** [comment]
Fixed in 5.0.3.0
