### ISSUE TITLE
No longer works with Office 365?

### ISSUE THREAD

**Issue by hthuong09** [3axap4eHko/OWA-pro#4]
I used to use this extension with Office 365. Since the latest update my account was forced log out and I can not add again. 
In "Server address", I put _https://outlook.office.com/owa/_. In email and username, I put my email.
It keeps saying "Invalid credentials".

I don't know if this I can help you. I opened Developer Tools and saw this
![image](https://cloud.githubusercontent.com/assets/8191266/17763314/aa360362-64cc-11e6-9dc0-7aaa64561116.png)
`%20:%20`, It seems pretty wrong to me.
I am using the latest version on _Windows 10_ and Chrome version _Version 52.0.2743.116 m_

**Comment by 3axap4eHko** [comment]
try to find solution here:
http://lmgtfy.com/?q=ews+server+office+365

**Comment by hthuong09** [comment]
Well, in your tutorial video you said just put the owa address.
And yes, I already did enter Office 365 exchange server (_https://outlook.office365.com/EWS/Exchange.asmx_).
It was saying the same. _Invalid credentials_

Request output
![image](https://cloud.githubusercontent.com/assets/8191266/17795471/788eff20-656d-11e6-83e8-f50ec2f3b5e8.png)

**Comment by 3axap4eHko** [comment]
Could you tell me version of extension?

**Comment by hthuong09** [comment]
It's `ver. 5.1.0.0`

**Comment by 3axap4eHko** [comment]
Try to update to Version: 5.1.1.0

**Comment by hthuong09** [comment]
Updated to version 5.1.1.0
Results:
![image](https://cloud.githubusercontent.com/assets/8191266/17797371/36c5b696-657d-11e6-97a0-e72f401aac17.png)
![image](https://cloud.githubusercontent.com/assets/8191266/17797390/62606152-657d-11e6-8b7e-fb3cc81ddd0b.png)

**Comment by 3axap4eHko** [comment]
Exactly! Check your credentials.
try to open this url and input your credentials into window like this
![image](https://cloud.githubusercontent.com/assets/1630657/17797509/651e25c2-6597-11e6-85bb-3366e86cfd78.png)
If your credentials is valid this windows should hide

**Comment by hthuong09** [comment]
I am able to login directly to exchange server by enter email/password to that prompt.
![image](https://cloud.githubusercontent.com/assets/8191266/17797613/1f799f14-657f-11e6-9ae6-c47f36b4fa9c.png)

**Comment by 3axap4eHko** [comment]
try to use provided url for the setup form?

**Comment by hthuong09** [comment]
Still getting _Invalid credentials_
![image](https://cloud.githubusercontent.com/assets/8191266/17797705/df8be690-657f-11e6-9eb5-b59864267056.png)

**Comment by 3axap4eHko** [comment]
I'm sorry, but I don't have an office365 account, so I don't know how to resolve you problem right now. But could you try to open provided url in browser?

**Comment by hthuong09** [comment]
It says server DNS could not be found when I open it directly in browser.

**Comment by 3axap4eHko** [comment]
One more question, do you have domain at your email account?
If you have, try to input username like: DOMAIN\username

**Comment by hthuong09** [comment]
Yes, I do. My email is like user@mycompany.com. I tried to put mycompany\user but still the same.
Btw: It works on the OWA Notifier (I use _Load unpacked extension_) with this configuration.
![image](https://cloud.githubusercontent.com/assets/8191266/17798180/f0dfe960-6583-11e6-8557-830e6ceea1e2.png)

![image](https://cloud.githubusercontent.com/assets/8191266/17798194/0c510f76-6584-11e6-8a0a-844ffe8b4df2.png)

**Comment by sidharth2592** [comment]
i am also having the same issue

**Comment by janusn** [comment]
I have encountered the same issue though my account is not an Office 365 but a corporate account like hthuong09.

**Comment by alex-steinberg** [comment]
I am experiencing the same issue, though I only just installed the extension.

**Comment by 3axap4eHko** [comment]
Would be great if somebody provide me office365 account to discover it

**Comment by andre-morassut** [comment]
Same issue for me :(

@3axap4eHko : Sadly, I cannot provide, at this time, an office365 account.

**Comment by dustinsharp** [comment]
@3axap4eHko I'm having the same issue as well. Since my account is corporate, I cannot allow access to it, but I'm hoping this new information might help.

It appears that I'm getting authentication errors in the common.js file. I ran the pretty print feature of Chrome debugger and determined that it was line 1314 that was throwing the errors. Perhaps that would be a place to start? I can't guarantee that this is the same issue that other people are having though. Might just be that I can't figure out the settings I need.

Here's a screen grab of the specific errors I'm encountering:

![image](https://cloud.githubusercontent.com/assets/12186033/21523420/b1c249d2-ccd3-11e6-9db4-fdf91344b90a.png)

**Comment by omrebel** [comment]
@dustinsharp Were you able to get this working? The company I work for just switched over to OWA, and this extension could be a life saver if it works. I'm also getting the Invalid credentials error when trying to use it.

**Comment by dustinsharp** [comment]
Sorry, @omrebel. No luck.

**Comment by 3axap4eHko** [comment]
fixed
