### ISSUE TITLE
Uncaught promise error

### ISSUE THREAD

**Issue by grit96** [3axap4eHko/OWA-pro#5]
When I specify the correct EWS URL, there is an error that prevents the setup from completing and the modal stalls on "Loading folders...":
![image](https://cloud.githubusercontent.com/assets/3957608/17790067/da7552c4-658c-11e6-808e-9c5281b6993e.png)

This happens after a 401 response then the successful responses with Authorization header:
![image](https://cloud.githubusercontent.com/assets/3957608/17790424/4b5dad14-658e-11e6-8769-6a99eb4b185b.png)

Inspecting the error reveals the error message to be "Invalid server response 200: OK".

**Comment by 3axap4eHko** [comment]
401 is fine. This is a NTLM authorization requirements

**Comment by 3axap4eHko** [comment]
Could you provide extension version?

**Comment by grit96** [comment]
ver. 5.0.3.0

**Comment by grit96** [comment]
ver. 5.0.3.0

**Comment by grit96** [comment]
It used to work fine with OWA Notifier.

**Comment by 3axap4eHko** [comment]
Do you use self-signed certificate?

**Comment by grit96** [comment]
No
