### ISSUE TITLE
UI broken?

### ISSUE THREAD

**Issue by AcidReptile** [3axap4eHko/OWA-pro#6]
Is it normal in UI?
![2016-08-22 09_11_24-](https://cloud.githubusercontent.com/assets/10757466/17845168/994bf942-6848-11e6-8adc-eaa7366a159d.png)
Software: Latest Yandex.Browser

**Comment by 3axap4eHko** [comment]
Нет, никогда не тестировалось для этого браузера. Используйте stable google chrome пожалуйста
