### ISSUE TITLE
Chrome Barely Usable

### ISSUE THREAD

**Issue by FireCode20** [3axap4eHko/OWA-pro#9]
Extension: 5.2.6.0
Windows: 8.1
Chrome: 54.0.2840.7
Errors: No Visible Errors...

So this is a weird bug that *Might* be down to how the mail server works here, but when I try to open chrome it grinds to a halt taking 4 to 10 seconds to load the new tab page. The settings I using are: 00:00:05 for both the Update Interval and the Notification Lifetime, and I am using an EWS/OWA (I had to enter both to set the extension up) mail server. I have tried making the Update Interval longer but at 00:00:30 and 00:01:00 it still ran chrome into the ground. Hope this helps.

**Comment by 3axap4eHko** [comment]
It happens if response time of mail server is greater than 5 seconds, so once you set values back just go to [chrome://extensions/?id=hldldpjjjagjfikfknadmnnmpbbhgihg](chrome://extensions/?id=hldldpjjjagjfikfknadmnnmpbbhgihg) and click **Reload** link
